### ISSUE TITLE
Static build MacOs Laravel logs

### ISSUE THREAD

**Issue by alterwalker** [dunglas/frankenphp#677]
### What happened?

I've compiled static build of my Laravel application, started it, making requests, but application responses with 500 error from application.

When try to use artisan command, got error:

```
mac-o@Mac-mini-mac-o frankenphp % ./dist/frankenphp-mac-arm64 php-cli artisan    

   Error 

  Call to undefined function Symfony\Component\Mailer\Transport\Smtp\filter_var()

  at /private/var/folders/84/q0c2xhlx2vx__893spvtk5lm0000gn/T/frankenphp_43065c5d8ab6bc83cacc88fa104fcd00/vendor/symfony/mailer/Transport/Smtp/EsmtpTransportFactory.php:36

   Error 

  Call to undefined function NunoMaduro\Collision\token_get_all()

  at /private/var/folders/84/q0c2xhlx2vx__893spvtk5lm0000gn/T/frankenphp_43065c5d8ab6bc83cacc88fa104fcd00/vendor/nunomaduro/collision/src/Highlighter.php:135

   Symfony\Component\ErrorHandler\Error\FatalError 

  Uncaught Error: Call to undefined function NunoMaduro\Collision\token_get_all() in /private/var/folders/84/q0c2xhlx2vx__893spvtk5lm0000gn/T/frankenphp_43065c5d8ab6bc83cacc88fa104fcd00/vendor/nunomaduro/collision/src/Highlighter.php:135
Stack trace:
#0 /private/var/folders/84/q0c2xhlx2vx__893spvtk5lm0000gn/T/frankenphp_43065c5d8ab6bc83cacc88fa104fcd00/vendor/nunomaduro/collision/src/Highlighter.php(128): NunoMaduro\Collision\Highlighter->tokenize('<?php\n\ndeclare(...')
#1 /private/var/folders/84/q0c2xhlx2vx__893spvtk5lm0000gn/T/frankenphp_43065c5d8ab6bc83cacc88fa104fcd00/vendor/nunomaduro/collision/src/Highlighter.php(113): NunoMaduro\Collision\Highlighter->getHighlightedLines('<?php\n\ndeclare(...')
#2 /private/var/folders/84/q0c2xhlx2vx__893spvtk5lm0000gn/T/frankenphp_43065c5d8ab6bc83cacc88fa104fcd00/vendor/nunomaduro/collision/src/Highlighter.php(105): NunoMaduro\Collision\Highlighter->getCodeSnippet('<?php\n\ndeclare(...', 135, 4, 4)
#3 /private/var/folders/84/q0c2xhlx2vx__893spvtk5lm0000gn/T/frankenphp_43065c5d8ab6bc83cacc88fa104fcd00/vendor/nunomaduro/collision/src/Writer.php(265): NunoMaduro\Collision\Highlighter->highlight('<?php\n\ndeclare(...', 135)
#4 /private/var/folders/84/q0c2xhlx2vx__893spvtk5lm0000gn/T/frankenphp_43065c5d8ab6bc83cacc88fa104fcd00/vendor/nunomaduro/collision/src/Writer.php(108): NunoMaduro\Collision\Writer->renderEditor(Object(Whoops\Exception\Frame))
#5 /private/var/folders/84/q0c2xhlx2vx__893spvtk5lm0000gn/T/frankenphp_43065c5d8ab6bc83cacc88fa104fcd00/vendor/nunomaduro/collision/src/Handler.php(35): NunoMaduro\Collision\Writer->write(Object(Whoops\Exception\Inspector))
#6 /private/var/folders/84/q0c2xhlx2vx__893spvtk5lm0000gn/T/frankenphp_43065c5d8ab6bc83cacc88fa104fcd00/vendor/filp/whoops/src/Whoops/Run.php(398): NunoMaduro\Collision\Handler->handle(Object(Error))
#7 [internal function]: Whoops\Run->handleException(Object(Error))
#8 {main}
  thrown

  at /private/var/folders/84/q0c2xhlx2vx__893spvtk5lm0000gn/T/frankenphp_43065c5d8ab6bc83cacc88fa104fcd00/vendor/nunomaduro/collision/src/Highlighter.php:135

   Error 

  Call to undefined function NunoMaduro\Collision\token_get_all()

  at /private/var/folders/84/q0c2xhlx2vx__893spvtk5lm0000gn/T/frankenphp_43065c5d8ab6bc83cacc88fa104fcd00/vendor/nunomaduro/collision/src/Highlighter.php:135
mac-o@Mac-mini-mac-o frankenphp % 

```

Where I can find Laravel log directory? STDOUT is empty too.

### Build Type

Official static build

### Worker Mode

Yes

### Operating System

macOS

### CPU Architecture

Apple Silicon

### PHP configuration

```shell
php 8.3
```

**Comment by crazywhalecc** [comment]
Maybe missing `tokenizer` and `filter` extension.

**Comment by alterwalker** [comment]
I've installed pure Laravel and tried to create static build. It really tells me about `filter` extension, but I've declared to install it.
```
EMBED=../../laravel-example-app PHP_EXTENSIONS=ctype,iconv,pdo,pdo_mysql,mbstring,exif,pcntl,bcmath,gd,sockets,gmp,phpenmod,opcache,redis,filter ./build-static.sh
```

Now main question is - where I can find laravel logs, when using static build?

**Comment by henderkes** [comment]
In /tmp/embedded-app-hash/var/log/...


Closing this because it's very old, if you still have an issue with this please raise it again.
