### ISSUE TITLE
Error while make binary in MacOs

### ISSUE THREAD

**Issue by grandrr** [dunglas/frankenphp#726]
### What happened?

I got issue while run command:
`./build-static.sh`
on MacOs

### Build Type

Standalone binary

### Worker Mode

Yes

### Operating System

macOS

### CPU Architecture

x86_64

### PHP configuration

```shell
8.3.3
```

### Relevant log output

```shell
Installing dependencies from lock file
Verifying lock file contents can be installed on current platform.
Nothing to install, update or remove
Generating optimized autoload files
8 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
     _        _   _                 _           
 ___| |_ __ _| |_(_) ___      _ __ | |__  _ __  
/ __| __/ _` | __| |/ __|____| '_ \| '_ \| '_ \ 
\__ \ || (_| | |_| | (_|_____| |_) | | | | |_) |
|___/\__\__,_|\__|_|\___|    | .__/|_| |_| .__/   v2.2.0
                             |_|         |_|    
Checking if current OS are supported ... Darwin x86_64, supported
Checking if homebrew has installed ... ok
Checking if necessary tools are installed ... ok
Doctor check complete !
     _        _   _                 _           
 ___| |_ __ _| |_(_) ___      _ __ | |__  _ __  
/ __| __/ _` | __| |/ __|____| '_ \| '_ \| '_ \ 
\__ \ || (_| | |_| | (_|_____| |_) | | | | |_) |
|___/\__\__,_|\__|_|\___|    | .__/|_| |_| .__/   v2.2.0
                             |_|         |_|    
[09:15:45] [INFO] Fetching source php-src [1/35]
[09:15:49] [INFO] Fetching source micro [2/35]
[09:15:49] [NOTI] source [micro] already downloaded: micro
[09:15:49] [INFO] Fetching source pkg-config [3/35]
[09:15:49] [NOTI] source [pkg-config] already downloaded: pkg-config-0.29.2.tar.gz
[09:15:49] [INFO] Fetching source apcu [4/35]
[09:15:49] [NOTI] source [apcu] already downloaded: apcu.tgz
[09:15:49] [INFO] Fetching source igbinary [5/35]
[09:15:49] [NOTI] source [igbinary] already downloaded: igbinary.tgz
[09:15:49] [INFO] Fetching source redis [6/35]
[09:15:49] [NOTI] source [redis] already downloaded: redis
[09:15:49] [INFO] Fetching source bzip2 [7/35]
[09:15:49] [NOTI] source [bzip2] already downloaded: bzip2-1.0.8.tar.gz
[09:15:49] [INFO] Fetching source zlib [8/35]
[09:15:49] [NOTI] source [zlib] already downloaded: zlib-1.3.1.tar.gz
[09:15:49] [INFO] Fetching source openssl [9/35]
[09:15:49] [NOTI] source [openssl] already downloaded: openssl-3.3.0.tar.gz
[09:15:49] [INFO] Fetching source libssh2 [10/35]
[09:15:49] [NOTI] source [libssh2] already downloaded: libssh2-1.11.0.tar.gz
[09:15:49] [INFO] Fetching source brotli [11/35]
[09:15:49] [NOTI] source [brotli] already downloaded: google-brotli-dev-null-0-g91d1b2d.tar.gz
[09:15:49] [INFO] Fetching source libiconv [12/35]
[09:15:49] [NOTI] source [libiconv] already downloaded: libiconv-1.17.tar.gz
[09:15:49] [INFO] Fetching source xz [13/35]
[09:15:49] [NOTI] source [xz] already downloaded: xz-5.4.6.tar.xz
[09:15:49] [INFO] Fetching source icu [14/35]
[09:15:49] [NOTI] source [icu] already downloaded: icu4c-74_2-src.tgz
[09:15:49] [INFO] Fetching source libxml2 [15/35]
[09:15:49] [NOTI] source [libxml2] already downloaded: v2.12.5.tar.gz
[09:15:49] [INFO] Fetching source nghttp2 [16/35]
[09:15:49] [NOTI] source [nghttp2] already downloaded: nghttp2-1.61.0.tar.xz
[09:15:49] [INFO] Fetching source zstd [17/35]
[09:15:49] [NOTI] source [zstd] already downloaded: zstd-1.5.6.tar.gz
[09:15:49] [INFO] Fetching source curl [18/35]
[09:15:49] [NOTI] source [curl] already downloaded: curl-8.7.1.tar.xz
[09:15:49] [INFO] Fetching source qdbm [19/35]
[09:15:49] [NOTI] source [qdbm] already downloaded: qdbm
[09:15:49] [INFO] Fetching source libpng [20/35]
[09:15:49] [NOTI] source [libpng] already downloaded: libpng
[09:15:49] [INFO] Fetching source libavif [21/35]
[09:15:49] [NOTI] source [libavif] already downloaded: AOMediaCodec-libavif-v1.0.4-0-gd77cfec.tar.gz
[09:15:49] [INFO] Fetching source libwebp [22/35]
[09:15:49] [NOTI] source [libwebp] already downloaded: v1.3.2.tar.gz
[09:15:49] [INFO] Fetching source libjpeg [23/35]
[09:15:49] [NOTI] source [libjpeg] already downloaded: libjpeg-turbo-libjpeg-turbo-3.0.2-0-g289df64.tar.gz
[09:15:49] [INFO] Fetching source freetype [24/35]
[09:15:49] [NOTI] source [freetype] already downloaded: freetype
[09:15:49] [INFO] Fetching source gmp [25/35]
[09:15:49] [NOTI] source [gmp] already downloaded: alisw-GMP-v6.2.1-0-g2bbd527.tar.gz
[09:15:49] [INFO] Fetching source libsodium [26/35]
[09:15:49] [NOTI] source [libsodium] already downloaded: libsodium-1.0.19.tar.gz
[09:15:49] [INFO] Fetching source ldap [27/35]
[09:15:49] [NOTI] source [ldap] already downloaded: openldap-2.6.7.tgz
[09:15:49] [INFO] Fetching source onig [28/35]
[09:15:49] [NOTI] source [onig] already downloaded: onig-6.9.9.tar.gz
[09:15:49] [INFO] Fetching source ncurses [29/35]
[09:15:49] [NOTI] source [ncurses] already downloaded: ncurses-6.4.tar.gz
[09:15:49] [INFO] Fetching source readline [30/35]
[09:15:49] [NOTI] source [readline] already downloaded: readline-8.2.tar.gz
[09:15:49] [INFO] Fetching source libxslt [31/35]
[09:15:49] [NOTI] source [libxslt] already downloaded: libxslt-1.1.39.tar.xz
[09:15:49] [INFO] Fetching source postgresql [32/35]
[09:15:49] [NOTI] source [postgresql] already downloaded: postgresql-16.2.tar.bz2
[09:15:49] [INFO] Fetching source sqlite [33/35]
[09:15:49] [NOTI] source [sqlite] already downloaded: sqlite-autoconf-3430200.tar.gz
[09:15:49] [INFO] Fetching source liblz4 [34/35]
[09:15:49] [NOTI] source [liblz4] already downloaded: lz4-1.9.4.tar.gz
[09:15:49] [INFO] Fetching source libzip [35/35]
[09:15:49] [NOTI] source [libzip] already downloaded: libzip-1.10.1.tar.xz
[09:15:49] [INFO] Download complete, used 4.173 s !
     _        _   _                 _           
 ___| |_ __ _| |_(_) ___      _ __ | |__  _ __  
/ __| __/ _` | __| |/ __|____| '_ \| '_ \| '_ \ 
\__ \ || (_| | |_| | (_|_____| |_) | | | | |_) |
|___/\__\__,_|\__|_|\___|    | .__/|_| |_| .__/   v2.2.0
                             |_|         |_|    
[09:15:49] [DEBU] Setting env: BUILD_ROOT_PATH=/Users/volodymyrustinov/frankenphp/dist/static-php-cli/buildroot
[09:15:49] [DEBU] Setting env: BUILD_INCLUDE_PATH=/Users/volodymyrustinov/frankenphp/dist/static-php-cli/buildroot/include
[09:15:49] [DEBU] Setting env: BUILD_LIB_PATH=/Users/volodymyrustinov/frankenphp/dist/static-php-cli/buildroot/lib
[09:15:49] [DEBU] Setting env: BUILD_BIN_PATH=/Users/volodymyrustinov/frankenphp/dist/static-php-cli/buildroot/bin
[09:15:49] [DEBU] Setting env: PKG_ROOT_PATH=/Users/volodymyrustinov/frankenphp/dist/static-php-cli/pkgroot
[09:15:49] [DEBU] Setting env: SOURCE_PATH=/Users/volodymyrustinov/frankenphp/dist/static-php-cli/source
[09:15:49] [DEBU] Setting env: DOWNLOAD_PATH=/Users/volodymyrustinov/frankenphp/dist/static-php-cli/downloads
[09:15:49] [INFO] [EXEC] sysctl -n hw.ncpu
[09:15:49] [DEBU] Setting env: SPC_CONCURRENCY=12
[09:15:49] [DEBU] Setting env: CC=clang
[09:15:49] [DEBU] Setting env: CXX=clang++
[09:15:49] [DEBU] Setting env: SPC_DEFAULT_C_FLAGS=--target=x86_64-apple-darwin
[09:15:49] [DEBU] Setting env: SPC_DEFAULT_CXX_FLAGS=--target=x86_64-apple-darwin
[09:15:49] [DEBU] Setting env: SPC_EXTRA_LIBS=
[09:15:49] [DEBU] Setting env: SPC_CMD_PREFIX_PHP_BUILDCONF=./buildconf --force
[09:15:49] [DEBU] Setting env: SPC_CMD_PREFIX_PHP_CONFIGURE=./configure --prefix= --with-valgrind=no --enable-shared=no --enable-static=yes --disable-all --disable-cgi --disable-phpdbg
[09:15:49] [DEBU] Setting env: SPC_CMD_PREFIX_PHP_MAKE=make -j12
[09:15:49] [DEBU] Setting env: SPC_CMD_VAR_PHP_CONFIGURE_CFLAGS=--target=x86_64-apple-darwin -Werror=unknown-warning-option
[09:15:49] [DEBU] Setting env: SPC_CMD_VAR_PHP_CONFIGURE_CPPFLAGS=-I/Users/volodymyrustinov/frankenphp/dist/static-php-cli/buildroot/include
[09:15:49] [DEBU] Setting env: SPC_CMD_VAR_PHP_CONFIGURE_LDFLAGS=-L/Users/volodymyrustinov/frankenphp/dist/static-php-cli/buildroot/lib
[09:15:49] [DEBU] Setting env: SPC_CMD_VAR_PHP_MAKE_EXTRA_CFLAGS=-g -Os
[09:15:49] [DEBU] Setting env: SPC_CMD_VAR_PHP_MAKE_EXTRA_LIBS=-lresolv
[09:15:49] [DEBU] Setting env: PATH=/Users/volodymyrustinov/frankenphp/dist/static-php-cli/buildroot/bin:/Users/volodymyrustinov/.nvm/versions/node/v21.6.0/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
[09:15:49] [DEBU] Setting env: PKG_CONFIG=/Users/volodymyrustinov/frankenphp/dist/static-php-cli/buildroot/bin/pkg-config
[09:15:49] [DEBU] Setting env: PKG_CONFIG_PATH=/Users/volodymyrustinov/frankenphp/dist/static-php-cli/buildroot/lib/pkgconfig
[09:15:49] [DEBU] making cmake tool chain file for Darwin x86_64 with CFLAGS='--target=x86_64-apple-darwin'
[09:15:49] [DEBU] Dir /Users/volodymyrustinov/frankenphp/dist/static-php-cli/buildroot/lib/pkgconfig already exists, ignored
[09:15:49] [DEBU] Dir /Users/volodymyrustinov/frankenphp/dist/static-php-cli/buildroot/include already exists, ignored
[09:15:49] [INFO] Build OS:        Darwin (x86_64)
[09:15:49] [INFO] Build SAPI:      embed
[09:15:49] [INFO] Extensions (44): apcu,bcmath,bz2,calendar,ctype,curl,dba,dom,exif,fileinfo,filter,zlib,gd,iconv,igbinary,intl,openssl,ldap,mbstring,mbregex,mysqlnd,mysqli,opcache,pcntl,pdo,pdo_mysql,pgsql,pdo_pgsql,sqlite3,pdo_sqlite,phar,posix,readline,session,redis,simplexml,sockets,sodium,sysvsem,tokenizer,xml,xmlreader,xmlwriter,zip
[09:15:49] [INFO] Libraries (23):  bzip2,zlib,openssl,brotli,libiconv,icu,libxml2,curl,libpng,libavif,libwebp,libjpeg,freetype,gmp,libsodium,ldap,onig,ncurses,readline,postgresql,sqlite,liblz4,libzip
[09:15:49] [INFO] Strip Binaries:  yes
[09:15:49] [INFO] Enable ZTS:      yes
[09:15:49] [INFO] PHP Version:     8.3.6
[09:15:49] [DEBU] Init var [BUILD_ROOT_PATH]:                    /Users/volodymyrustinov/frankenphp/dist/static-php-cli/buildroot
[09:15:49] [DEBU] Init var [BUILD_INCLUDE_PATH]:                 /Users/volodymyrustinov/frankenphp/dist/static-php-cli/buildroot/include
[09:15:49] [DEBU] Init var [BUILD_LIB_PATH]:                     /Users/volodymyrustinov/frankenphp/dist/static-php-cli/buildroot/lib
[09:15:49] [DEBU] Init var [BUILD_BIN_PATH]:                     /Users/volodymyrustinov/frankenphp/dist/static-php-cli/buildroot/bin
[09:15:49] [DEBU] Init var [PKG_ROOT_PATH]:                      /Users/volodymyrustinov/frankenphp/dist/static-php-cli/pkgroot
[09:15:49] [DEBU] Init var [SOURCE_PATH]:                        /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source
[09:15:49] [DEBU] Init var [DOWNLOAD_PATH]:                      /Users/volodymyrustinov/frankenphp/dist/static-php-cli/downloads
[09:15:49] [DEBU] Init var [SPC_CONCURRENCY]:                    12
[09:15:49] [DEBU] Init var [CC]:                                 clang
[09:15:49] [DEBU] Init var [CXX]:                                clang++
[09:15:49] [DEBU] Init var [SPC_DEFAULT_C_FLAGS]:                --target=x86_64-apple-darwin
[09:15:49] [DEBU] Init var [SPC_DEFAULT_CXX_FLAGS]:              --target=x86_64-apple-darwin
[09:15:49] [DEBU] Init var [SPC_EXTRA_LIBS]:                     
[09:15:49] [DEBU] Init var [SPC_CMD_PREFIX_PHP_BUILDCONF]:       ./buildconf --force
[09:15:49] [DEBU] Init var [SPC_CMD_PREFIX_PHP_CONFIGURE]:       ./configure --prefix= --with-valgrind=no --enable-shared=no --enable-static=yes --disable-all --disable-cgi --disable-phpdbg
[09:15:49] [DEBU] Init var [SPC_CMD_PREFIX_PHP_MAKE]:            make -j12
[09:15:49] [DEBU] Init var [SPC_CMD_VAR_PHP_CONFIGURE_CFLAGS]:   --target=x86_64-apple-darwin -Werror=unknown-warning-option
[09:15:49] [DEBU] Init var [SPC_CMD_VAR_PHP_CONFIGURE_CPPFLAGS]: -I/Users/volodymyrustinov/frankenphp/dist/static-php-cli/buildroot/include
[09:15:49] [DEBU] Init var [SPC_CMD_VAR_PHP_CONFIGURE_LDFLAGS]:  -L/Users/volodymyrustinov/frankenphp/dist/static-php-cli/buildroot/lib
[09:15:49] [DEBU] Init var [SPC_CMD_VAR_PHP_MAKE_EXTRA_CFLAGS]:  -g -Os
[09:15:49] [DEBU] Init var [SPC_CMD_VAR_PHP_MAKE_EXTRA_LIBS]:    -lresolv
[09:15:49] [DEBU] Init var [PATH]:                               /Users/volodymyrustinov/frankenphp/dist/static-php-cli/buildroot/bin:/Users/volodymyrustinov/.nvm/versions/node/v21.6.0/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin
[09:15:49] [DEBU] Init var [PKG_CONFIG]:                         /Users/volodymyrustinov/frankenphp/dist/static-php-cli/buildroot/bin/pkg-config
[09:15:49] [DEBU] Init var [PKG_CONFIG_PATH]:                    /Users/volodymyrustinov/frankenphp/dist/static-php-cli/buildroot/lib/pkgconfig
[09:15:49] [NOTI] Build will start after 2s ...
[09:15:51] [DEBU] scanning directory /Users/volodymyrustinov/frankenphp/dist/static-php-cli/src/SPC/builder/macos/library
[09:15:52] [DEBU] enabling libxml2 without xz
[09:15:52] [DEBU] enabling curl without libssh2
[09:15:52] [DEBU] enabling curl without nghttp2
[09:15:52] [DEBU] enabling curl without zstd
[09:15:52] [DEBU] enabling postgresql without libxslt
[09:15:52] [DEBU] enabling postgresql without zstd
[09:15:52] [DEBU] enabling libzip without xz
[09:15:52] [DEBU] enabling libzip without zstd
[09:15:52] [DEBU] Source [pkg-config] already extracted in /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/pkg-config, skip !
[09:15:52] [DEBU] Source [bzip2] already extracted in /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/bzip2, skip !
[09:15:52] [DEBU] Source [zlib] already extracted in /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/zlib, skip !
[09:15:52] [DEBU] Source [openssl] already extracted in /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/openssl, skip !
[09:15:52] [DEBU] Source [brotli] already extracted in /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/brotli, skip !
[09:15:52] [DEBU] Source [libiconv] already extracted in /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/libiconv, skip !
[09:15:52] [DEBU] Source [icu] already extracted in /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/icu, skip !
[09:15:52] [DEBU] Source [libxml2] already extracted in /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/libxml2, skip !
[09:15:52] [DEBU] Source [curl] already extracted in /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/curl, skip !
[09:15:52] [DEBU] Source [libpng] already extracted in /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/libpng, skip !
[09:15:52] [DEBU] Source [libavif] already extracted in /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/libavif, skip !
[09:15:52] [DEBU] Source [libwebp] already extracted in /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/libwebp, skip !
[09:15:52] [DEBU] Source [libjpeg] already extracted in /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/libjpeg, skip !
[09:15:52] [DEBU] Source [freetype] already extracted in /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/freetype, skip !
[09:15:52] [DEBU] Source [gmp] already extracted in /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/gmp, skip !
[09:15:52] [DEBU] Source [libsodium] already extracted in /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/libsodium, skip !
[09:15:52] [DEBU] Source [ldap] already extracted in /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/ldap, skip !
[09:15:52] [DEBU] Source [onig] already extracted in /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/onig, skip !
[09:15:52] [DEBU] Source [ncurses] already extracted in /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/ncurses, skip !
[09:15:52] [DEBU] Source [readline] already extracted in /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/readline, skip !
[09:15:52] [DEBU] Source [postgresql] already extracted in /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/postgresql, skip !
[09:15:52] [DEBU] Source [sqlite] already extracted in /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/sqlite, skip !
[09:15:52] [DEBU] Source [liblz4] already extracted in /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/liblz4, skip !
[09:15:52] [DEBU] Source [libzip] already extracted in /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/libzip, skip !
[09:15:52] [NOTI] lib [pkg-config] already built
[09:15:52] [NOTI] lib [bzip2] already built
[09:15:52] [NOTI] lib [zlib] already built
[09:15:52] [NOTI] lib [openssl] already built
[09:15:52] [NOTI] lib [brotli] already built
[09:15:52] [NOTI] lib [libiconv] already built
[09:15:52] [NOTI] lib [icu] already built
[09:15:52] [NOTI] lib [libxml2] already built
[09:15:52] [NOTI] lib [curl] already built
[09:15:52] [NOTI] lib [libpng] already built
[09:15:52] [NOTI] lib [libavif] already built
[09:15:52] [NOTI] lib [libwebp] already built
[09:15:52] [NOTI] lib [libjpeg] already built
[09:15:52] [NOTI] lib [freetype] already built
[09:15:52] [INFO] Building required library [gmp]
[09:15:52] [INFO] Entering dir: /Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/gmp
[09:15:52] [INFO] [EXEC]  ./configure --enable-static --disable-shared --prefix=
[09:15:52] [DEBU] Running command with direct output: cd '/Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/gmp' &&  ./configure --enable-static --disable-shared --prefix=
checking build system type... kabylake-apple-darwin23.4.0
checking host system type... kabylake-apple-darwin23.4.0
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking ABI=64
checking whether clang is gcc... yes
checking compiler clang -O2 -pedantic -fomit-frame-pointer -m64 ... yes
checking compiler clang -O2 -pedantic -fomit-frame-pointer -m64  -mtune=skylake... yes
checking compiler clang -O2 -pedantic -fomit-frame-pointer -m64 -mtune=skylake  -march=broadwell... yes
checking for gcc... clang
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether clang accepts -g... yes
checking for clang option to accept ISO C89... none needed
checking whether clang understands -c and -o together... yes
checking for clang option to accept ISO C99... none needed
checking how to run the C preprocessor... clang -E
checking build system compiler clang... yes
checking for build system preprocessor... clang -E
checking for build system executable suffix... 
checking whether build system compiler is ANSI... yes
checking for build system compiler math library... -lm
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
using ABI="64"
      CC="clang"
      CFLAGS="-O2 -pedantic -fomit-frame-pointer -m64 -mtune=skylake -march=broadwell"
      CPPFLAGS=""
      MPN_PATH=" x86_64/skylake x86_64/coreibwl x86_64/coreihwl x86_64/coreisbr x86_64/coreinhm x86_64/core2 x86_64 generic"
checking whether assembler supports --noexecstack option... no
checking for ar... ar
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for fgrep... /usr/bin/grep -F
checking for ld used by clang... /Library/Developer/CommandLineTools/usr/bin/ld
checking if the linker (/Library/Developer/CommandLineTools/usr/bin/ld) is GNU ld... no
checking whether ln -s works... yes
checking the maximum length of command line arguments... 786432
checking how to convert kabylake-apple-darwin23.4.0 file names to kabylake-apple-darwin23.4.0 format... func_convert_file_noop
checking how to convert kabylake-apple-darwin23.4.0 file names to toolchain format... func_convert_file_noop
checking for /Library/Developer/CommandLineTools/usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... dlltool
checking how to associate runtime and link libraries... printf %s\n
checking for archiver @FILE support... no
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from clang object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for lipo... lipo
checking for otool... otool
checking for otool64... no
checking for -single_module linker flag... ld: warning: -single_module is obsolete
no
checking for -exported_symbols_list linker flag... yes
checking for -force_load linker flag... yes
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if clang supports -fno-rtti -fno-exceptions... yes
checking for clang option to produce PIC... -fno-common -DPIC
checking if clang PIC flag -fno-common -DPIC works... yes
checking if clang static flag -static works... no
checking if clang supports -c -o file.o... yes
checking if clang supports -c -o file.o... (cached) yes
checking whether the clang linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin23.4.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... no
checking whether to build static libraries... yes
checking how to run the C++ preprocessor... clang++ -E
checking whether the clang++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... no
checking for clang++ option to produce PIC...  -DPIC
checking if clang++ PIC flag  -DPIC works... yes
checking if clang++ static flag  works... yes
checking if clang++ supports -c -o file.o... yes
checking if clang++ supports -c -o file.o... (cached) yes
checking whether the clang++ linker (/Library/Developer/CommandLineTools/usr/bin/ld) supports shared libraries... no
checking dynamic linker characteristics... darwin23.4.0 dyld
checking how to hardcode library paths into programs... immediate
checking for ANSI C header files... (cached) yes
checking whether time.h and sys/time.h may both be included... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking float.h usability... yes
checking float.h presence... yes
checking for float.h... yes
checking invent.h usability... no
checking invent.h presence... no
checking for invent.h... no
checking langinfo.h usability... yes
checking langinfo.h presence... yes
checking for langinfo.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking nl_types.h usability... yes
checking nl_types.h presence... yes
checking for nl_types.h... yes
checking sys/attributes.h usability... no
checking sys/attributes.h presence... no
checking for sys/attributes.h... no
checking sys/iograph.h usability... no
checking sys/iograph.h presence... no
checking for sys/iograph.h... no
checking sys/mman.h usability... yes
checking sys/mman.h presence... yes
checking for sys/mman.h... yes
checking sys/param.h usability... yes
checking sys/param.h presence... yes
checking for sys/param.h... yes
checking sys/processor.h usability... no
checking sys/processor.h presence... no
checking for sys/processor.h... no
checking sys/pstat.h usability... no
checking sys/pstat.h presence... no
checking for sys/pstat.h... no
checking sys/sysinfo.h usability... no
checking sys/sysinfo.h presence... no
checking for sys/sysinfo.h... no
checking sys/syssgi.h usability... no
checking sys/syssgi.h presence... no
checking for sys/syssgi.h... no
checking sys/systemcfg.h usability... no
checking sys/systemcfg.h presence... no
checking for sys/systemcfg.h... no
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking sys/times.h usability... yes
checking sys/times.h presence... yes
checking for sys/times.h... yes
checking for sys/resource.h... yes
checking for sys/sysctl.h... yes
checking for machine/hal_sysinfo.h... no
checking whether fgetc is declared... yes
checking whether fscanf is declared... yes
checking whether optarg is declared... yes
checking whether ungetc is declared... yes
checking whether vfprintf is declared... yes
checking whether sys_errlist is declared... yes
checking whether sys_nerr is declared... yes
checking return type of signal handlers... void
checking for intmax_t... yes
checking for long double... yes
checking for long long... yes
checking for ptrdiff_t... yes
checking for quad_t... yes
checking for uint_least32_t... yes
checking for intptr_t... yes
checking for working volatile... yes
checking for C/C++ restrict keyword... __restrict
checking whether gcc __attribute__ ((const)) works... yes
checking whether gcc __attribute__ ((malloc)) works... yes
checking whether gcc __attribute__ ((mode (XX))) works... yes
checking whether gcc __attribute__ ((noreturn)) works... yes
checking whether gcc hidden aliases work... no
checking for inline... inline
checking for working alloca.h... yes
checking for alloca (via gmp-impl.h)... yes
checking how to allocate temporary memory... alloca
checking whether byte ordering is bigendian... no
checking format of `double' floating point... IEEE little endian
checking for alarm... yes
checking for attr_get... no
checking for clock... yes
checking for cputime... no
checking for getpagesize... yes
checking for getrusage... yes
checking for gettimeofday... yes
checking for getsysinfo... no
checking for localeconv... yes
checking for memset... yes
checking for mmap... yes
checking for mprotect... yes
checking for nl_langinfo... yes
checking for obstack_vprintf... no
checking for popen... yes
checking for processor_info... yes
checking for pstat_getprocessor... no
checking for raise... yes
checking for read_real_time... no
checking for sigaction... yes
checking for sigaltstack... yes
checking for sigstack... no
checking for syssgi... no
checking for strchr... yes
checking for strerror... yes
checking for strnlen... yes
checking for strtol... yes
checking for strtoul... yes
checking for sysconf... yes
checking for sysctl... yes
checking for sysctlbyname... yes
checking for times... yes
checking for library containing clock_gettime... none required
checking for vsnprintf... yes
checking whether vsnprintf works... yes
checking whether sscanf needs writable input... no
checking for struct pst_processor.psp_iticksperclktick... no
checking for suitable m4... configure: error: No usable m4 in $PATH or /usr/5bin (see config.log for reasons).
[09:16:55] [ERRO] Uncaught SPC\exception\RuntimeException: Command run failed with code[1]: cd '/Users/volodymyrustinov/frankenphp/dist/static-php-cli/source/gmp' &&  ./configure --enable-static --disable-shared --prefix= at /Users/volodymyrustinov/frankenphp/dist/static-php-cli/src/globals/functions.php(100)
[09:16:55] [ERRO] #0 /Users/volodymyrustinov/frankenphp/dist/static-php-cli/src/SPC/util/UnixShell.php(47): f_passthru('cd '/Users/volo...')
#1 /Users/volodymyrustinov/frankenphp/dist/static-php-cli/src/SPC/util/UnixShell.php(79): SPC\util\UnixShell->exec('cd '/Users/volo...')
#2 /Users/volodymyrustinov/frankenphp/dist/static-php-cli/src/SPC/builder/unix/library/gmp.php(20): SPC\util\UnixShell->execWithEnv('./configure --e...')
#3 /Users/volodymyrustinov/frankenphp/dist/static-php-cli/src/SPC/builder/LibraryBase.php(144): SPC\builder\macos\library\gmp->build()
#4 /Users/volodymyrustinov/frankenphp/dist/static-php-cli/src/SPC/builder/LibraryBase.php(152): SPC\builder\LibraryBase->tryBuild(true)
#5 /Users/volodymyrustinov/frankenphp/dist/static-php-cli/src/SPC/builder/unix/UnixBuilderBase.php(143): SPC\builder\LibraryBase->tryBuild(false)
#6 /Users/volodymyrustinov/frankenphp/dist/static-php-cli/src/SPC/command/BuildCliCommand.php(144): SPC\builder\unix\UnixBuilderBase->buildLibs(Array)
#7 /Users/volodymyrustinov/frankenphp/dist/static-php-cli/src/SPC/command/BaseCommand.php(99): SPC\command\BuildCliCommand->handle()
#8 /Users/volodymyrustinov/frankenphp/dist/static-php-cli/vendor/symfony/console/Command/Command.php(326): SPC\command\BaseCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /Users/volodymyrustinov/frankenphp/dist/static-php-cli/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /Users/volodymyrustinov/frankenphp/dist/static-php-cli/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(SPC\command\BuildCliCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /Users/volodymyrustinov/frankenphp/dist/static-php-cli/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /Users/volodymyrustinov/frankenphp/dist/static-php-cli/bin/spc(21): Symfony\Component\Console\Application->run()
#13 {main}
```

**Comment by dunglas** [comment]
Can you try `brew install m4`?

**Comment by grandrr** [comment]
yes, i had try this, its try install m4, tell that its installed, but this does not help. i think this is related to my local machine, so i will close it
