### ISSUE TITLE
Misinterpretation of PHP script

### ISSUE THREAD

**Issue by J-Cake** [dunglas/frankenphp#842]
### What happened?

I'm running (trying) to run NextCloud on FrankenPHP, which has been working for the most part, but when running the included Console script, I get a syntax error that there is content before the `<?php` section and should be removed. But there isn't. 

Added by @withinboredom:

```php
<?php

var_dump(headers_sent());
```

`headers_sent()` returns `true` in cli-mode.

### Build Type

Official static build

### Worker Mode

No

### Operating System

GNU/Linux

### CPU Architecture

x86_64

### PHP configuration

```shell
Please see [phpinfo.php](https://nextcloud.jschneiderprojects.au/phpinfo.php)

Please let me know when you have viewed this, so I can take it down
```

### Relevant log output

```shell
$ docker exec -it jcake-nextcloud-1 frankenphp php-cli /app/occ files:scan
An unhandled exception has been thrown:
Exception: Config file has leading content, please remove everything before "<?php" in config.php in /app/lib/private/Config.php:257
Stack trace:
#0 /app/lib/private/Config.php(71): OC\Config->readData()
#1 /app/lib/base.php(150): OC\Config->__construct('/app/config/')
#2 /app/lib/base.php(622): OC::initPaths()
#3 /app/lib/base.php(1181): OC::init()
#4 /app/console.php(48): require_once('/app/lib/base.p...')
#5 /app/occ(11): require_once('/app/console.ph...')
#6 {main}
```
```

**Comment by withinboredom** [comment]
> But there isn't.

There may very well be hidden data that you cannot see in your text editor (non-printable characters, for example) or maybe whatever is reading the config is misinterpreting a BOM. Also, if there are any PHP errors in your config, it's possible it will detect this as input because PHP is outputting the error/warning.

**Comment by withinboredom** [comment]
This seems more like a nextcloud issue and not a frankenphp issue. Closing this.

**Comment by J-Cake** [comment]
[Hi I forgot to link the thread from the Nextcloud support forums](https://help.nextcloud.com/t/config-file-has-leading-content/194026/7). There are no non-printable characters. I proved this using a hexdump.

**Comment by withinboredom** [comment]
Updated the context to include the actual bug

**Comment by J-Cake** [comment]
> Updated the context to include the actual bug

Ah apologies... That would have been useful..

**Comment by hugo-akaora** [comment]
Actually it's more a workaround than anything but in Nextcloud server source you can comment lines between 216 and 223 in `lib/private/Config.php` and you won't be bothered anymore.

**Comment by J-Cake** [comment]
> Actually it's more a workaround than anything but in Nextcloud server source you can comment lines between 216 and 223 in `lib/private/Config.php` and you won't be bothered anymore.

my god. Even if it's a workaround it works! Thank uuu

**Comment by dunglas** [comment]
Is there any special character in these lines?

**Comment by J-Cake** [comment]
Nah it's just a check

**Comment by kesselb** [comment]
Hi,

Thanks for your work on FrankenPHP! I’m really looking forward to try it out - I just haven’t had the chance yet.

I've sent J-Cake to frankenphp because "headers_sent()" does return true even for cli requests.

Here’s what I’ve noticed so far:

- The Docker image (8cd0c8a23307) either seems fixed or was never affected.
- However, I can still reproduce the issue by running frankenphp php-cli test.php.

**test.php:**

```php
<?php

var_dump(headers_sent());
```

Hope this helps!

**Comment by dunglas** [comment]
Ok, it's in CLI mode! I missed that. We likely have a bug for this.

**Comment by ai-tp** [comment]
Any news on this? 
Its still happening in frankenphp v1.9.0
A fix would be greatly appreciated!

**Comment by withinboredom** [comment]
We're working on getting cli-mode to actually use the php-cli in 8.5 ... it's non-trivial (because php-cli adds some functions that shouldn't be available in other sapis) but it is in-progress.

**Comment by ai-tp** [comment]
Good to know, thank you for the information

**Comment by J-Cake** [comment]
I just wanted to let you folks know that I've had a very reliable experience with FrankenPHP since this issue arose simply by commenting out that check. Now with a fresh install the issue has resurfaced.

Even if it is a workaround, it seems to be fairly reliable...

**Comment by henderkes** [comment]
Sadly our plans for using real cli in frankenphp haven't made it upstream in php 8.5 yet, but I think there's a decent chance they make it into 8.6.
